<?xml version="1.0"?>
<!--
  Author:
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Macro for cable -->
  <xacro:macro name="cable" params="namespace cable_length cable_radius">

    <!-- Load bottom -->
    <link name="${namespace}/load_bottom">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia
         ixx="0.0001" ixy="0.0" ixz="0.0"
         iyy="0.0001" iyz="0.0"
         izz="0.0001"/>
      </inertial>
    </link>

    <!-- Load bottom intermediate-->
    <link name="${namespace}/load_bottom2">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia
         ixx="0.0001" ixy="0.0" ixz="0.0"
         iyy="0.0001" iyz="0.0"
         izz="0.0001"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${cable_length}" radius="${cable_radius}"/>
        </geometry>
      </visual>
    </link>

    <!-- Joint bewteen load_bottom and load_top -->
    <!-- Joint that rotates freely around the second body axis-->    
    <joint name="${namespace}/joint_load1_load2" type="continuous">
      <parent link="${namespace}/load_bottom"/>
      <child link="${namespace}/load_bottom2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Load top -->
    <link name="${namespace}/load_top">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia
         ixx="0.0001" ixy="0.0" ixz="0.0"
         iyy="0.0001" iyz="0.0"
         izz="0.0001"/>
      </inertial>
    </link>

    <!-- Joint bewteen load_bottom and load_top -->
    <!-- Joint that rotates freely around the second body axis-->    
    <joint name="${namespace}/joint_load2_load3" type="continuous">
      <parent link="${namespace}/load_bottom2"/>
      <child link="${namespace}/load_top"/>
      <origin xyz="0 0 ${cable_length}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

  </xacro:macro>

</robot>