<?xml version="1.0"?>
<!--
  Author: Massimiliano Pandolfo

  Description: This file merges the functionalities of firefly.xacro and firefly_base.xacro in a single file, and embeds the code in a macro, which can be called by an external file.

  ##############################################################################

  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <!-- <xacro:property name="namespace" value="$(arg mav_name)" /> -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://neo_description/meshes/neo.dae" />
  <xacro:property name="mass" value="2.662" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.2" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.234" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.005" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.2495" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.028" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1143" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="6.8e-06" /> <!-- [kg m/s^2] -->
  <xacro:property name="moment_constant" value="0.016754" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0182" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.0182" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1047.2" /> <!-- [rad/s] -->
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="front_propeller_x" value="0.213" />
  <xacro:property name="front_propeller_y" value="0.12988" />
  <xacro:property name="side_propeller_x" value="-0.00067" />
  <xacro:property name="side_propeller_y" value="0.24939" />
  <xacro:property name="back_propeller_x" value="-0.21561" />
  <xacro:property name="back_propeller_y" value="0.12535" />
  <xacro:property name="rotor_drag_coefficient" value="2.0673e-04" />
  <xacro:property name="rolling_moment_coefficient" value="0.0" />
  <!-- Manipulator arm -->
  <xacro:property name="mass_link1" value="0.0578000000000000" /> <!-- [kg] -->
  <xacro:property name="mass_link2" value="0.0463000000000000" /> <!-- [kg] -->
  <xacro:property name="mass_link3" value="0.0358000000000000" /> <!-- [kg] -->
  <xacro:property name="mass_link4" value="0.0250000000000000" /> <!-- [kg] -->
  <xacro:property name="mass_end_effector" value="0.038" /> <!-- [kg] -->
  <xacro:property name="inertia_zz_link1" value="0.000253151228084876" /> <!-- [kg*m^2] -->
  <xacro:property name="inertia_zz_link2" value="0.000108770447476707" /> <!-- [kg*m^2] -->
  <xacro:property name="inertia_zz_link3" value="3.47458286569986e-05" /> <!-- [kg*m^2] -->
  <xacro:property name="inertia_zz_link4" value="3.42053994711421e-05" /> <!-- [kg*m^2] -->
  <xacro:property name="length_x_link1" value="0.173000000000000" /> <!-- [m] -->
  <xacro:property name="length_x_link2" value="0.122000000000000" /> <!-- [m] -->
  <xacro:property name="length_x_link3" value="0.0711000000000000" /> <!-- [m] -->
  <xacro:property name="length_x_link4" value="0.0200000000000000" /> <!-- [m] -->
  <xacro:property name="length_x_end_effector" value="0.05" /> <!-- [m] -->
  <xacro:property name="width_link1" value="0.069" /> <!-- [m] -->
  <xacro:property name="width_link2" value="0.055" /> <!-- [m] -->
  <xacro:property name="width_link3" value="0.035" /> <!-- [m] -->
  <xacro:property name="width_link4" value="0.028" /> <!-- [m] -->
  <xacro:property name="thickness" value="0.028" /> <!-- [m] -->
  <xacro:property name="diameter_end_effector" value="0.018" /> <!-- [m] -->
  <xacro:property name="manipulator_position_z" value="-0.0" /> <!-- [m] -->
  <!-- chosen as a tenth of the friction... -->
  <xacro:property name="damping" value="0.03" /> <!-- [(N*m)/(rad/s)] -->
  <!-- chosen as half of the torque the base joint requires to keep the arm horizontal... -->
  <xacro:property name="friction" value="0.3" /> <!-- [N*m] -->
  <!-- effort: gearmotor torque = 5 kg*cm, bevel gear ratio is 1:2, so 1 N*m -->
  <xacro:property name="effort" value="1" /> <!-- [N*m] -->

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia ixx="0.0341171" ixy="0.0" ixz="0.0" iyy="0.0363089" iyz="0.0" izz="0.0627386" /> <!-- [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] -->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/multirotor_base.xacro" />

  <xacro:include filename="$(find rotors_description)/urdf/component_snippets.xacro" />
<!--
      _ __ ___     __ _    ___   _ __    ___  
     | '_ ` _ \   / _` |  / __| | '__|  / _ \ 
     | | | | | | | (_| | | (__  | |    | (_) |
     |_| |_| |_|  \__,_|  \___| |_|     \___/ 
-->
  <xacro:macro name="uav_macro" params="namespace">

    <!-- ################################################################### -->
    <!-- ##                        neo.xacro                          ## -->
    <!-- ################################################################### -->

    <!-- Instantiate multirotor_base_macro once -->
    <xacro:multirotor_base_macro
      robot_namespace="${namespace}"
      mass="${mass}"
      body_width="${body_width}"
      body_height="${body_height}"
      use_mesh_file="${use_mesh_file}"
      mesh_file="${mesh_file}"
      >
      <xacro:insert_block name="body_inertia" />
    </xacro:multirotor_base_macro>

    <!-- Instantiate rotors -->
    <xacro:vertical_rotor
      robot_namespace="${namespace}"
      suffix="front_left"
      direction="ccw"
      motor_constant="${motor_constant}"
      moment_constant="${moment_constant}"
      parent="${namespace}/base_link"
      mass_rotor="${mass_rotor}"
      radius_rotor="${radius_rotor}"
      time_constant_up="${time_constant_up}"
      time_constant_down="${time_constant_down}"
      max_rot_velocity="${max_rot_velocity}"
      motor_number="0"
      rotor_drag_coefficient="${rotor_drag_coefficient}"
      rolling_moment_coefficient="${rolling_moment_coefficient}"
      color="Red"
      use_own_mesh="true"
      mesh="package://neo_description/meshes/propeller_ccw.dae">
      <origin xyz="${cos30*arm_length} ${sin30*arm_length} ${rotor_offset_top}" rpy="${5*pi/180} 0 ${30*pi/180}" />
      <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor
      robot_namespace="${namespace}"
      suffix="left"
      direction="cw"
      motor_constant="${motor_constant}"
      moment_constant="${moment_constant}"
      parent="${namespace}/base_link"
      mass_rotor="${mass_rotor}"
      radius_rotor="${radius_rotor}"
      time_constant_up="${time_constant_up}"
      time_constant_down="${time_constant_down}"
      max_rot_velocity="${max_rot_velocity}"
      motor_number="1"
      rotor_drag_coefficient="${rotor_drag_coefficient}"
      rolling_moment_coefficient="${rolling_moment_coefficient}"
      color="Blue"
      use_own_mesh="true"
      mesh="package://neo_description/meshes/propeller_cw.dae">
      <origin xyz="0 ${arm_length} ${rotor_offset_top}" rpy="0 ${-5*pi/180} 0" />
      <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor robot_namespace="${namespace}"
      suffix="back_left"
      direction="ccw"
      motor_constant="${motor_constant}"
      moment_constant="${moment_constant}"
      parent="${namespace}/base_link"
      mass_rotor="${mass_rotor}"
      radius_rotor="${radius_rotor}"
      time_constant_up="${time_constant_up}"
      time_constant_down="${time_constant_down}"
      max_rot_velocity="${max_rot_velocity}"
      motor_number="2"
      rotor_drag_coefficient="${rotor_drag_coefficient}"
      rolling_moment_coefficient="${rolling_moment_coefficient}"
      color="Blue"
      use_own_mesh="true"
      mesh="package://neo_description/meshes/propeller_ccw.dae">
      <origin xyz="-${cos30*arm_length} ${sin30*arm_length} ${rotor_offset_top}" rpy="${5*pi/180} 0 ${150*pi/180}" />
      <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor robot_namespace="${namespace}"
      suffix="back_right"
      direction="cw"
      motor_constant="${motor_constant}"
      moment_constant="${moment_constant}"
      parent="${namespace}/base_link"
      mass_rotor="${mass_rotor}"
      radius_rotor="${radius_rotor}"
      time_constant_up="${time_constant_up}"
      time_constant_down="${time_constant_down}"
      max_rot_velocity="${max_rot_velocity}"
      motor_number="3"
      rotor_drag_coefficient="${rotor_drag_coefficient}"
      rolling_moment_coefficient="${rolling_moment_coefficient}"
      color="Blue"
      use_own_mesh="true"
      mesh="package://neo_description/meshes/propeller_cw.dae">
      <origin xyz="-${cos30*arm_length} -${sin30*arm_length} ${rotor_offset_top}" rpy="${-5*pi/180} 0 ${-150*pi/180}" />
      <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor
      robot_namespace="${namespace}"
      suffix="right"
      direction="ccw"
      motor_constant="${motor_constant}"
      moment_constant="${moment_constant}"
      parent="${namespace}/base_link"
      mass_rotor="${mass_rotor}"
      radius_rotor="${radius_rotor}"
      time_constant_up="${time_constant_up}"
      time_constant_down="${time_constant_down}"
      max_rot_velocity="${max_rot_velocity}"
      motor_number="4"
      rotor_drag_coefficient="${rotor_drag_coefficient}"
      rolling_moment_coefficient="${rolling_moment_coefficient}"
      color="Blue"
      use_own_mesh="true"
      mesh="package://neo_description/meshes/propeller_ccw.dae">
      <origin xyz="0 -${arm_length} ${rotor_offset_top}" rpy="0 ${5*pi/180} ${pi}" />
      <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor
      robot_namespace="${namespace}"
      suffix="front_right"
      direction="cw"
      motor_constant="${motor_constant}"
      moment_constant="${moment_constant}"
      parent="${namespace}/base_link"
      mass_rotor="${mass_rotor}"
      radius_rotor="${radius_rotor}"
      time_constant_up="${time_constant_up}"
      time_constant_down="${time_constant_down}"
      max_rot_velocity="${max_rot_velocity}"
      motor_number="5"
      rotor_drag_coefficient="${rotor_drag_coefficient}"
      rolling_moment_coefficient="${rolling_moment_coefficient}"
      color="Red"
      use_own_mesh="true"
      mesh="package://neo_description/meshes/propeller_cw.dae">
      <origin xyz="${cos30*arm_length} -${sin30*arm_length} ${rotor_offset_top}" rpy="${-5*pi/180} 0 ${-30*pi/180}" />
      <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <!-- ################################################################### -->
    <!-- ##                      neo_base.xacro                       ## -->
    <!-- ################################################################### -->

    <!-- Instantiate a controller. -->
    <xacro:controller_plugin_macro namespace="${namespace}" imu_sub_topic="imu" />

    <!-- Mount an ADIS16448 IMU. -->
    <xacro:default_imu namespace="${namespace}" parent_link="${namespace}/base_link" />

    <xacro:if value="$(arg enable_ground_truth)">
      <xacro:ground_truth_imu_and_odometry namespace="${namespace}" parent_link="${namespace}/base_link" />
    </xacro:if>

    <xacro:if value="$(arg enable_logging)">
      <!-- Instantiate a logger -->
      <xacro:bag_plugin_macro
        namespace="${namespace}"
        bag_file="$(arg log_file)"
        rotor_velocity_slowdown_sim="${rotor_velocity_slowdown_sim}" />
    </xacro:if>

  </xacro:macro>

</robot>
