# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: carma/joint1
  pid: {p: 4.0, i: 0.5, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: carma/joint2
  pid: {p: 1.0, i: 0.5, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: carma/joint3
  pid: {p: 1.0, i: 0.5, d: 0.001, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: carma/joint4
  pid: {p: 1.0, i: 0.5, d: 0.001, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: carma/joint5
  pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}

